Bump aws-cdk-lib from 2.116.0 to 2.116.1 (#212)
Bumps
[aws-cdk-lib](https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib)
from 2.116.0 to 2.116.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/aws/aws-cdk/releases">aws-cdk-lib's
releases</a>.</em></p>
<blockquote>
<h2>v2.116.1</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> core constructs fail with <code>Error: Cannot
find module '../dist/core/&lt;file&gt;.generated'</code> (<a
href="https://redirect.github.com/aws/aws-cdk/issues/28467">#28467</a>)
(<a
href="https://github.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933">e8be128</a>),
closes <a
href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a>
<a
href="https://redirect.github.com/aws/aws-cdk/issues/28465">#28465</a></li>
</ul>
<hr />
<h2>Alpha modules (2.116.1-alpha.0)</h2>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/aws/aws-cdk/blob/main/CHANGELOG.v2.md">aws-cdk-lib's
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/aws/aws-cdk/compare/v2.116.0...v2.116.1">2.116.1</a>
(2023-12-22)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> core constructs fail with <code>Error: Cannot
find module '../dist/core/&lt;file&gt;.generated'</code> (<a
href="https://redirect.github.com/aws/aws-cdk/issues/28467">#28467</a>)
(<a
href="https://github.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933">e8be128</a>),
closes <a
href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a>
<a
href="https://redirect.github.com/aws/aws-cdk/issues/28465">#28465</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933"><code>e8be128</code></a>
fix(core): core constructs fail with `Error: Cannot find module
'../dist/core...</li>
<li>See full diff in <a
href="https://github.com/aws/aws-cdk/commits/v2.116.1/packages/aws-cdk-lib">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=aws-cdk-lib&package-manager=npm_and_yarn&previous-version=2.116.0&new-version=2.116.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>